<?php

return [
    'admin.home' => '首页',
    // Apps Modules
    'admin.apps.index' => '小程序管理',
    'admin.apps.create' => '添加小程序',
    'admin.apps.show' => '小程序详情',
    'admin.apps.edit' => '编辑小程序',
    // Topics Modules
    'admin.topics.index' => '专题管理',
    'admin.topics.create' => '添加专题',
    'admin.topics.show' => '专题详情',
    'admin.topics.edit' => '编辑专题',
    // Members Modules
    'admin.members.index' => '会员管理',
    'admin.members.create' => '添加会员',
    'admin.members.show' => '会员详情',
    'admin.members.edit' => '编辑会员',
    // Ad Positions Modules
    'admin.ad_positions.index' => '广告位管理',
    'admin.ad_positions.create' => '添加广告位',
    'admin.ad_positions.show' => '广告位详情',
    'admin.ad_positions.edit' => '编辑广告位',
    // Comments Modules
    'admin.comments.index' => '评论管理',
    'admin.comments.create' => '添加评论',
    'admin.comments.show' => '评论详情',
    'admin.comments.edit' => '编辑评论',
    // Replies Modules
    'admin.replies.index' => '回复管理',
    'admin.replies.create' => '添加回复',
    'admin.replies.show' => '回复详情',
    'admin.replies.edit' => '编辑回复',
    // Sms Modules
    'admin.sms.index' => '短信记录',
    // Categories Modules
    'admin.categories.index' => '分类管理',
    'admin.categories.create' => '添加分类',
    'admin.categories.show' => '分类详情',
    'admin.categories.edit' => '编辑分类',
    // Ads Modules
    'admin.ads.index' => '广告管理',
    'admin.ads.create' => '添加广告',
    'admin.ads.show' => '广告详情',
    'admin.ads.edit' => '编辑广告',
    // Keywords Modules
    'admin.keywords.index' => '关键词管理',
    'admin.keywords.create' => '添加关键词',
    'admin.keywords.show' => '关键词详情',
    'admin.keywords.edit' => '编辑关键词',
    // Modules Modules
    'admin.modules.index' => '模块管理',
    'admin.modules.create' => '添加模块',
    'admin.modules.show' => '模块详情',
    'admin.modules.edit' => '编辑模块',
    // Modulegables Modules
    'admin.modulegables.index' => '模块关联管理',
    'admin.modulegables.show' => '模块关联详情',
    'admin.modulegables.edit' => '编辑模块关联',
    // AppCategory Modules
    'admin.app_category.index' => '小程序和分类关联管理',
    'admin.app_category.show' => '小程序和分类关联详情',
    'admin.app_category.edit' => '编辑小程序和分类关联',
    // AppTopic Modules
    'admin.app_topic.index' => '小程序和专题关联管理',
    'admin.app_topic.show' => '小程序和专题关联详情',
    'admin.app_topic.edit' => '编辑小程序和专题关联',
    // Settings Modules
    'admin.settings.index' => '设置管理',
    'admin.settings.create' => '添加设置',
    'admin.settings.show' => '设置详情',
    'admin.settings.edit' => '编辑设置',
];